### ISSUE TITLE
New 1.5.3 version released

### ISSUE THREAD

**Issue by mariushosting** [marverix/classicpress-docker#2]
https://github.com/ClassicPress/ClassicPress-release/releases/tag/1.5.3

Hello @marverix please update to the latest version 1.5.3

**Comment by marverix** [comment]
Hello, version please use `cp1.5.3-rev2`. `rev2` includes docker layers optimization which reduced a number of fetched layers from 35 to 16 (most of those layers now are reusables from parent docker php-apache image).

BTW, the process of auto-update was automated, but because GitHub's Workflow cron scheduler is not reliable, I need to find another way to automate it...
